"""Chapter-leading 'you will learn' three-sentence summary (feature 9)."""

from __future__ import annotations

import re

from utils.ask_tutorial import HEADING_RE

SKIP = re.compile(r"^(#|<!--|>|\*source:|```|---|Generated by)")


def _sentences(text: str) -> list[str]:
    blobs: list[str] = []
    for line in (text or "").splitlines():
        stripped = line.strip()
        if not stripped or SKIP.match(stripped) or stripped.startswith("*"):
            continue
        blobs.append(stripped)
        if len(blobs) >= 8:
            break
    joined = " ".join(blobs)
    parts = [p.strip() for p in re.split(r"[。.!?\n]", joined) if 8 <= len(p.strip()) <= 120]
    return parts[:3]


def learning_outcomes(text: str, *, language: str = "Chinese") -> list[str]:
    items = _sentences(text)
    heading = HEADING_RE.search(text or "")
    title = heading.group(1).strip() if heading else "本章"
    if not items:
        items = [f"理解 {title} 解决什么问题", f"能指出 {title} 对应的源文件", f"知道读完后该看哪一章"]
    while len(items) < 3:
        items.append(f"巩固与 {title} 相关的代码路径")
    return items[:3]


def outcomes_markdown(text: str, *, language: str = "Chinese") -> str:
    label = "你将学到" if (language or "").lower().startswith("ch") else "You will learn"
    bullets = "\n".join(f"- {item}" for item in learning_outcomes(text, language=language))
    return f"> **{label}**\n{bullets}\n"


def inject_outcomes(text: str, *, language: str = "Chinese") -> str:
    if "你将学到" in (text or "") or "You will learn" in (text or ""):
        return text
    block = outcomes_markdown(text, language=language)
    match = HEADING_RE.search(text or "")
    if not match:
        return block + "\n" + (text or "")
    end = match.end()
    return (text or "")[:end] + "\n\n" + block + (text or "")[end:]
