"""One-click static site for GitHub Pages (index.html + .nojekyll)."""

from __future__ import annotations

import html
import re
import shutil
from pathlib import Path

from utils.ask_tutorial import HEADING_RE
from web.render import markdown_to_html

SKIP_MD = {"glossary.md", "heatmap.md"}
HREF_ABS = re.compile(r'href="/t/([^/]+)/([^"]+)"')


def _title_of(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = HEADING_RE.search(text)
    return match.group(1).strip() if match else path.stem


def _html_name(md_name: str) -> str:
    if md_name in {"index.md", "README.md"}:
        return "index.html"
    return Path(md_name).with_suffix(".html").name


def _rewrite_relative(body: str, tutorial: str) -> str:
    def repl(match: re.Match[str]) -> str:
        name, filename = match.group(1), match.group(2)
        if name != tutorial:
            return match.group(0)
        return f'href="{html.escape(_html_name(filename), quote=True)}"'

    return HREF_ABS.sub(repl, body)


def _page_shell(title: str, nav: str, body: str) -> str:
    return (
        "<!DOCTYPE html><html lang='zh-CN'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(title)}</title>"
        "<style>"
        "body{font-family:Georgia,serif;max-width:860px;margin:2rem auto;padding:0 1rem;line-height:1.65;color:#1e293b}"
        "nav a{margin-right:0.8rem}pre{overflow:auto;background:#f6f8fa;padding:1rem}"
        "h1,h2{border-bottom:1px solid #e2e8f0}footer{margin-top:3rem;color:#64748b;font-size:0.9rem}"
        "</style></head><body>"
        f"<nav>{nav}</nav>"
        f"{body}"
        "<footer>Generated by Quick Study · GitHub Pages</footer>"
        "</body></html>"
    )


def build_pages_site(folder: Path, dest: Path | None = None) -> Path:
    root = Path(folder)
    site = Path(dest) if dest is not None else root / "site"
    if site.exists():
        shutil.rmtree(site)
    site.mkdir(parents=True, exist_ok=True)
    (site / ".nojekyll").write_text("", encoding="utf-8")

    chapters = [
        path
        for path in sorted(root.glob("*.md"))
        if path.name not in SKIP_MD
    ]
    tutorial = root.name
    nav_parts = []
    for path in chapters:
        nav_parts.append(
            f"<a href='{html.escape(_html_name(path.name))}'>{html.escape(_title_of(path))}</a>"
        )
    nav = " ".join(nav_parts)

    written = []
    for path in chapters:
        text = path.read_text(encoding="utf-8")
        rendered = markdown_to_html(
            text, tutorial, cover=path.name in {"index.md", "README.md"}
        )
        if isinstance(rendered, tuple):
            body = rendered[0]
        else:
            body = rendered
        body = _rewrite_relative(body, tutorial)
        page = _page_shell(_title_of(path), nav, body)
        out = site / _html_name(path.name)
        out.write_text(page, encoding="utf-8")
        written.append(out.name)

    return site


def pages_file_list(site: Path) -> list[str]:
    root = Path(site)
    if not root.is_dir():
        return []
    names = [path.name for path in sorted(root.iterdir())]
    return names
