import { SCHEMA_VERSION } from "./types.ts";

type JsonSchema = Record<string, unknown>;

const stringOrNull = { type: ["string", "null"] };

/**
 * JSON Schema (draft 2020-12) for the analyzer output. The schema is part of the package
 * contract: consumers such as the Python repository analyzer validate against it, so any
 * breaking change requires a new `SCHEMA_VERSION`.
 */
export function getOutputSchema(): JsonSchema {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `https://quick-study.local/schemas/ts-analyzer/${SCHEMA_VERSION}/analysis.json`,
    title: "Quick Study TypeScript analysis",
    type: "object",
    additionalProperties: false,
    required: [
      "schemaVersion",
      "tool",
      "root",
      "files",
      "symbols",
      "imports",
      "dependencies",
      "callEdges",
      "diagnostics",
      "limits",
      "stats",
      "timing",
    ],
    properties: {
      schemaVersion: { type: "string", const: SCHEMA_VERSION },
      tool: {
        type: "object",
        additionalProperties: false,
        required: ["name", "version", "typescript"],
        properties: {
          name: { type: "string" },
          version: { type: "string" },
          typescript: { type: "string" },
        },
      },
      root: {
        type: "string",
        description: "Absolute analysis root. Environment dependent; every other path is relative to it.",
      },
      files: { type: "array", items: { $ref: "#/$defs/file" } },
      symbols: { type: "array", items: { $ref: "#/$defs/symbol" } },
      imports: { type: "array", items: { $ref: "#/$defs/import" } },
      dependencies: { type: "array", items: { $ref: "#/$defs/dependency" } },
      callEdges: { type: "array", items: { $ref: "#/$defs/callEdge" } },
      diagnostics: { type: "array", items: { $ref: "#/$defs/diagnostic" } },
      limits: {
        type: "object",
        additionalProperties: false,
        required: ["applied", "truncated", "truncationReasons"],
        properties: {
          applied: { $ref: "#/$defs/limits" },
          truncated: { type: "boolean" },
          truncationReasons: { type: "array", items: { type: "string" } },
        },
      },
      stats: { $ref: "#/$defs/stats" },
      timing: {
        type: "object",
        additionalProperties: false,
        required: ["durationMs"],
        description: "The only non-deterministic part of the document.",
        properties: { durationMs: { type: "integer", minimum: 0 } },
      },
    },
    $defs: {
      confidence: {
        type: "string",
        enum: ["high", "medium", "low"],
        description:
          "high: a unique top-level declaration in the analysis set. medium: a class member that a subclass may override, or a call into a module outside the analysis set. low: not statically decidable.",
      },
      callResolution: {
        type: "string",
        enum: ["resolved", "external", "ambiguous", "unresolved"],
        description:
          "resolved: `to` (or `resolvedFile`) names a target inside the analysis set. external: the target is outside the analysis set. ambiguous: several candidate declarations. unresolved: dynamic dispatch, reflection or an untyped callee.",
      },
      importResolution: {
        type: "string",
        enum: ["internal", "external", "unresolved"],
      },
      range: {
        type: "object",
        additionalProperties: false,
        required: ["startLine", "startColumn", "endLine", "endColumn"],
        properties: {
          startLine: { type: "integer", minimum: 1 },
          startColumn: { type: "integer", minimum: 1 },
          endLine: { type: "integer", minimum: 1 },
          endColumn: { type: "integer", minimum: 1 },
        },
      },
      file: {
        type: "object",
        additionalProperties: false,
        required: ["path", "language", "bytes", "lines", "sha256", "syntaxErrors"],
        properties: {
          path: { type: "string" },
          language: {
            type: "string",
            enum: ["ts", "tsx", "mts", "cts", "js", "jsx", "mjs", "cjs"],
          },
          bytes: { type: "integer", minimum: 0 },
          lines: { type: "integer", minimum: 0 },
          sha256: { type: "string", pattern: "^[0-9a-f]{64}$" },
          syntaxErrors: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["message", "line", "column", "code"],
              properties: {
                message: { type: "string" },
                line: { type: "integer", minimum: 1 },
                column: { type: "integer", minimum: 1 },
                code: { type: "integer" },
              },
            },
          },
        },
      },
      symbol: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "name",
          "qualifiedName",
          "kind",
          "file",
          "range",
          "exported",
          "exportKind",
          "exportName",
          "isAsync",
          "isGenerator",
          "isStatic",
          "isAbstract",
          "parentId",
          "signature",
          "docSummary",
        ],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          qualifiedName: { type: "string" },
          kind: {
            type: "string",
            enum: [
              "function",
              "class",
              "method",
              "constructor",
              "getter",
              "setter",
              "property",
              "variable",
              "interface",
              "type-alias",
              "enum",
              "namespace",
            ],
          },
          file: { type: "string" },
          range: { $ref: "#/$defs/range" },
          exported: { type: "boolean" },
          exportKind: { type: ["string", "null"], enum: ["named", "default", null] },
          exportName: stringOrNull,
          isAsync: { type: "boolean" },
          isGenerator: { type: "boolean" },
          isStatic: { type: "boolean" },
          isAbstract: { type: "boolean" },
          parentId: stringOrNull,
          signature: stringOrNull,
          docSummary: stringOrNull,
        },
      },
      import: {
        type: "object",
        additionalProperties: false,
        required: [
          "file",
          "moduleSpecifier",
          "kind",
          "typeOnly",
          "resolution",
          "resolvedFile",
          "unresolvedReason",
          "bindings",
          "range",
        ],
        properties: {
          file: { type: "string" },
          moduleSpecifier: { type: "string" },
          kind: { type: "string", enum: ["static", "dynamic", "require", "re-export"] },
          typeOnly: { type: "boolean" },
          resolution: { $ref: "#/$defs/importResolution" },
          resolvedFile: stringOrNull,
          unresolvedReason: stringOrNull,
          bindings: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["imported", "local", "kind"],
              properties: {
                imported: { type: "string" },
                local: { type: "string" },
                kind: { type: "string", enum: ["named", "default", "namespace"] },
              },
            },
          },
          range: { $ref: "#/$defs/range" },
        },
      },
      dependency: {
        type: "object",
        additionalProperties: false,
        required: ["from", "to", "scope", "count"],
        properties: {
          from: { type: "string" },
          to: { type: "string" },
          scope: { type: "string", enum: ["internal", "external"] },
          count: { type: "integer", minimum: 1 },
        },
      },
      callEdge: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "from",
          "fromFile",
          "to",
          "resolvedFile",
          "calleeText",
          "calleeName",
          "resolution",
          "confidence",
          "reason",
          "callKind",
          "externalModule",
          "range",
        ],
        properties: {
          id: { type: "string" },
          from: { ...stringOrNull, description: "Caller symbol id, null at module top level." },
          fromFile: { type: "string" },
          to: {
            ...stringOrNull,
            description: "Callee symbol id. Never set unless resolution is `resolved`.",
          },
          resolvedFile: {
            ...stringOrNull,
            description: "Target file for resolved `dynamic-import` and `require` edges.",
          },
          calleeText: { type: "string" },
          calleeName: stringOrNull,
          resolution: { $ref: "#/$defs/callResolution" },
          confidence: { $ref: "#/$defs/confidence" },
          reason: {
            type: "string",
            enum: [
              "checker-unique-declaration",
              "checker-multiple-declarations",
              "declaration-outside-analysis-set",
              "external-module",
              "import-literal",
              "require-literal",
              "callee-type-any",
              "computed-member-access",
              "no-declaration-for-callee",
              "parameter-invocation",
              "local-binding",
              "dynamic-eval",
              "dynamic-import-non-literal",
              "require-non-literal",
            ],
          },
          callKind: {
            type: "string",
            enum: [
              "function",
              "method",
              "constructor",
              "dynamic-import",
              "require",
              "computed",
              "unknown",
            ],
          },
          externalModule: stringOrNull,
          range: { $ref: "#/$defs/range" },
        },
      },
      diagnostic: {
        type: "object",
        additionalProperties: false,
        required: ["severity", "code", "message", "path"],
        properties: {
          severity: { type: "string", enum: ["info", "warning", "error"] },
          code: { type: "string" },
          message: { type: "string" },
          path: stringOrNull,
        },
      },
      limits: {
        type: "object",
        additionalProperties: false,
        required: [
          "maxFiles",
          "maxFileBytes",
          "maxTotalBytes",
          "maxDirectoryDepth",
          "timeBudgetMs",
        ],
        properties: {
          maxFiles: { type: "integer", minimum: 0 },
          maxFileBytes: { type: "integer", minimum: 0 },
          maxTotalBytes: { type: "integer", minimum: 0 },
          maxDirectoryDepth: { type: "integer", minimum: 0 },
          timeBudgetMs: { type: "integer", minimum: 0 },
        },
      },
      stats: {
        type: "object",
        additionalProperties: false,
        required: [
          "fileCount",
          "totalBytes",
          "symbolCount",
          "importCount",
          "dependencyCount",
          "callEdgeCount",
          "resolvedCallEdgeCount",
          "externalCallEdgeCount",
          "unresolvedCallEdgeCount",
        ],
        properties: {
          fileCount: { type: "integer", minimum: 0 },
          totalBytes: { type: "integer", minimum: 0 },
          symbolCount: { type: "integer", minimum: 0 },
          importCount: { type: "integer", minimum: 0 },
          dependencyCount: { type: "integer", minimum: 0 },
          callEdgeCount: { type: "integer", minimum: 0 },
          resolvedCallEdgeCount: { type: "integer", minimum: 0 },
          externalCallEdgeCount: { type: "integer", minimum: 0 },
          unresolvedCallEdgeCount: { type: "integer", minimum: 0 },
        },
      },
    },
  };
}
